blank_issues_enabled: false
contact_links:
  - name: ❓ Red Hat Developer Hub JIRA
    url: https://issues.redhat.com/browse/RHDHBUGS
    about: Please report any redhat-developer/rhdh issues or feature requests in JIRA - https://issues.redhat.com/browse/RHDHBUGS
  - name: ❓ Red Hat Developer Hub Plugins
    url: https://issues.redhat.com/browse/RHDHBUGS
    about: Please report any issues with https://github.com/redhat-developer/rhdh-plugins in JIRA - https://issues.redhat.com/browse/RHDHBUGS
  - name: ❓ Backstage Community Plugins
    url: https://github.com/backstage/community-plugins/issues
    about: Please report any plugin issues or feature requests in https://github.com/backstage/community-plugins/issues
