# This file is for the mandatory PR job only (e2e-ocp-helm).
# It is applied by `helm upgrade` after the `values_showcase-rbac.yaml` is applied and only contains complementary differences for PRs.
# Note, that it overwrites the whole key that is present in this file.
# The only exception is global.dynamic.plugins, that gets merged with the base file.

# Disable orchestrator for PRs to speed up the mandatory presubmit job and avoid extra infra installs.
# Orchestrator dynamic plugins are disabled via post-processing (see rbac_deployment in utils.sh)
orchestrator: null
