name: E2E Bash

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths:
      - '.ibm/**'

jobs:
  lint:
    name: ShellCheck and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        working-directory: ./.ibm
        run: yarn install

      - name: Run ShellCheck check
        working-directory: ./.ibm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn shellcheck

      - name: Run Prettier check
        working-directory: ./.ibm
        run: yarn prettier:check
