name: E2E Tests

on:
  pull_request:
    paths:
      - 'e2e-tests/**'
  push:
    branches:
      - "main"
      - "release-*"
    paths:
      - 'e2e-tests/**'

jobs:
  lint:
    name: TSC, ESLint and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies root
        working-directory: .
        run: yarn install

      - name: Install dependencies e2e-tests
        working-directory: ./e2e-tests
        run: yarn install --mode=skip-build

      - name: Run TypeScript Compiler check
        working-directory: ./e2e-tests
        run: yarn tsc:check

      - name: Run ESLint check
        working-directory: ./e2e-tests
        run: yarn lint:check

      - name: Run Prettier check
        working-directory: ./e2e-tests
        run: yarn prettier:check
